[package]
name = "connhelpers"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "connhelpers"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.33.0"
cookie = "0.18.1"
